name: Update README

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

  workflow_run:
    workflows: ["Deploy Docs"]
    types:
      - completed

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}

      - name: Replace placeholder with GitHub Pages URL
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          GITHUB_PAGES_URL="https://${GITHUB_REPOSITORY_OWNER}.github.io/${REPO_NAME}/"
          sed -i "s|{{GITHUB_PAGES_URL}}|$GITHUB_PAGES_URL|g" README.md

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update README with GitHub Pages URL"
          git push origin HEAD:${{ github.ref_name }}
